name: Build and deploy code

on: [push, pull_request]

jobs:
  job1:
    runs_on: ubuntu-latest
    steps:
      - name: pulling git repo
        uses: actions/checkout@v2
      - name: say hi
        run: echo "hello world"
